# Generated by Django 4.1.5 on 2023-01-21 18:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Platform', '0003_post_owner_post_publication_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='text_content',
            field=models.CharField(max_length=500),
        ),
    ]
