# Generated by Django 4.1.5 on 2023-01-23 04:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Platform', '0005_radio'),
    ]

    operations = [
        migrations.CreateModel(
            name='Song',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('link', models.URLField()),
            ],
        ),
        migrations.AddField(
            model_name='radio',
            name='description',
            field=models.CharField(default='', max_length=500),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='radio',
            name='songs',
            field=models.ManyToManyField(blank=True, related_name='listeners', to='Platform.song'),
        ),
    ]
