# Generated by Django 4.1.5 on 2023-01-23 04:54

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Platform', '0006_song_radio_description_alter_radio_songs'),
    ]

    operations = [
        migrations.AlterField(
            model_name='radio',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='radios', to=settings.AUTH_USER_MODEL),
        ),
    ]
